/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface VotingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "castVote"
      | "createProposal"
      | "getProposal"
      | "getVotes"
      | "joinProposal"
      | "proposalCounter"
      | "proposals"
      | "semaphore"
      | "voted"
      | "votes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ProposalCreated" | "VoteCast" | "VoterAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "castVote",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [string, string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "joinProposal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "semaphore", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "voted",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votes",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "joinProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "semaphore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    creator: AddressLike,
    description: string,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    creator: string,
    description: string,
    endTime: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    creator: string;
    description: string;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    optionIndex: BigNumberish,
    nullifier: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    optionIndex: bigint,
    nullifier: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    optionIndex: bigint;
    nullifier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoterAddedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    groupId: BigNumberish,
    identityCommitment: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    groupId: bigint,
    identityCommitment: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    groupId: bigint;
    identityCommitment: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Voting extends BaseContract {
  connect(runner?: ContractRunner | null): Voting;
  waitForDeployment(): Promise<this>;

  interface: VotingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  castVote: TypedContractMethod<
    [
      _proposalId: BigNumberish,
      _optionIndex: BigNumberish,
      _nullifier: BigNumberish,
      _merkleTreeDepth: BigNumberish,
      _merkleTreeRoot: BigNumberish,
      _points: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  createProposal: TypedContractMethod<
    [_description: string, _options: string[], _duration: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getProposal: TypedContractMethod<
    [_proposalId: BigNumberish],
    [
      [bigint, string, string, string[], bigint, bigint, bigint] & {
        id: bigint;
        creator: string;
        description: string;
        options: string[];
        endTime: bigint;
        groupId: bigint;
        voteCount: bigint;
      }
    ],
    "view"
  >;

  getVotes: TypedContractMethod<
    [_proposalId: BigNumberish, _optionIndex: BigNumberish],
    [bigint],
    "view"
  >;

  joinProposal: TypedContractMethod<
    [_proposalId: BigNumberish, _identityCommitment: BigNumberish],
    [void],
    "nonpayable"
  >;

  proposalCounter: TypedContractMethod<[], [bigint], "view">;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        description: string;
        endTime: bigint;
        groupId: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  semaphore: TypedContractMethod<[], [string], "view">;

  voted: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  votes: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [
      _proposalId: BigNumberish,
      _optionIndex: BigNumberish,
      _nullifier: BigNumberish,
      _merkleTreeDepth: BigNumberish,
      _merkleTreeRoot: BigNumberish,
      _points: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [_description: string, _options: string[], _duration: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [_proposalId: BigNumberish],
    [
      [bigint, string, string, string[], bigint, bigint, bigint] & {
        id: bigint;
        creator: string;
        description: string;
        options: string[];
        endTime: bigint;
        groupId: bigint;
        voteCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotes"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _optionIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinProposal"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _identityCommitment: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposalCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        description: string;
        endTime: bigint;
        groupId: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "semaphore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "voted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "votes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;
  getEvent(
    key: "VoterAdded"
  ): TypedContractEvent<
    VoterAddedEvent.InputTuple,
    VoterAddedEvent.OutputTuple,
    VoterAddedEvent.OutputObject
  >;

  filters: {
    "ProposalCreated(uint256,address,string,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "VoteCast(uint256,uint256,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;

    "VoterAdded(uint256,uint256,uint256)": TypedContractEvent<
      VoterAddedEvent.InputTuple,
      VoterAddedEvent.OutputTuple,
      VoterAddedEvent.OutputObject
    >;
    VoterAdded: TypedContractEvent<
      VoterAddedEvent.InputTuple,
      VoterAddedEvent.OutputTuple,
      VoterAddedEvent.OutputObject
    >;
  };
}
