/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace ISemaphore {
  export type SemaphoreProofStruct = {
    merkleTreeDepth: BigNumberish;
    merkleTreeRoot: BigNumberish;
    nullifier: BigNumberish;
    message: BigNumberish;
    scope: BigNumberish;
    points: BigNumberish[];
  };

  export type SemaphoreProofStructOutput = [
    merkleTreeDepth: bigint,
    merkleTreeRoot: bigint,
    nullifier: bigint,
    message: bigint,
    scope: bigint,
    points: bigint[]
  ] & {
    merkleTreeDepth: bigint;
    merkleTreeRoot: bigint;
    nullifier: bigint;
    message: bigint;
    scope: bigint;
    points: bigint[];
  };
}

export interface ISemaphoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptGroupAdmin"
      | "addMember"
      | "addMembers"
      | "createGroup(address,uint256)"
      | "createGroup()"
      | "createGroup(address)"
      | "groupCounter"
      | "removeMember"
      | "updateGroupAdmin"
      | "updateGroupMerkleTreeDuration"
      | "updateMember"
      | "validateProof"
      | "verifyProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GroupMerkleTreeDurationUpdated" | "ProofValidated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptGroupAdmin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addMember",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addMembers",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createGroup(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createGroup()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createGroup(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "groupCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeMember",
    values: [BigNumberish, BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGroupAdmin",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGroupMerkleTreeDuration",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMember",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "validateProof",
    values: [BigNumberish, ISemaphore.SemaphoreProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [BigNumberish, ISemaphore.SemaphoreProofStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptGroupAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addMembers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createGroup(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createGroup()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createGroup(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "groupCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGroupAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGroupMerkleTreeDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;
}

export namespace GroupMerkleTreeDurationUpdatedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    oldMerkleTreeDuration: BigNumberish,
    newMerkleTreeDuration: BigNumberish
  ];
  export type OutputTuple = [
    groupId: bigint,
    oldMerkleTreeDuration: bigint,
    newMerkleTreeDuration: bigint
  ];
  export interface OutputObject {
    groupId: bigint;
    oldMerkleTreeDuration: bigint;
    newMerkleTreeDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofValidatedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    merkleTreeDepth: BigNumberish,
    merkleTreeRoot: BigNumberish,
    nullifier: BigNumberish,
    message: BigNumberish,
    scope: BigNumberish,
    points: BigNumberish[]
  ];
  export type OutputTuple = [
    groupId: bigint,
    merkleTreeDepth: bigint,
    merkleTreeRoot: bigint,
    nullifier: bigint,
    message: bigint,
    scope: bigint,
    points: bigint[]
  ];
  export interface OutputObject {
    groupId: bigint;
    merkleTreeDepth: bigint;
    merkleTreeRoot: bigint;
    nullifier: bigint;
    message: bigint;
    scope: bigint;
    points: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISemaphore extends BaseContract {
  connect(runner?: ContractRunner | null): ISemaphore;
  waitForDeployment(): Promise<this>;

  interface: ISemaphoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptGroupAdmin: TypedContractMethod<
    [groupId: BigNumberish],
    [void],
    "nonpayable"
  >;

  addMember: TypedContractMethod<
    [groupId: BigNumberish, identityCommitment: BigNumberish],
    [void],
    "nonpayable"
  >;

  addMembers: TypedContractMethod<
    [groupId: BigNumberish, identityCommitments: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  "createGroup(address,uint256)": TypedContractMethod<
    [admin: AddressLike, merkleTreeDuration: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  "createGroup()": TypedContractMethod<[], [bigint], "nonpayable">;

  "createGroup(address)": TypedContractMethod<
    [admin: AddressLike],
    [bigint],
    "nonpayable"
  >;

  groupCounter: TypedContractMethod<[], [bigint], "view">;

  removeMember: TypedContractMethod<
    [
      groupId: BigNumberish,
      identityCommitment: BigNumberish,
      merkleProofSiblings: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  updateGroupAdmin: TypedContractMethod<
    [groupId: BigNumberish, newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  updateGroupMerkleTreeDuration: TypedContractMethod<
    [groupId: BigNumberish, newMerkleTreeDuration: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateMember: TypedContractMethod<
    [
      groupId: BigNumberish,
      oldIdentityCommitment: BigNumberish,
      newIdentityCommitment: BigNumberish,
      merkleProofSiblings: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  validateProof: TypedContractMethod<
    [groupId: BigNumberish, proof: ISemaphore.SemaphoreProofStruct],
    [void],
    "nonpayable"
  >;

  verifyProof: TypedContractMethod<
    [groupId: BigNumberish, proof: ISemaphore.SemaphoreProofStruct],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptGroupAdmin"
  ): TypedContractMethod<[groupId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addMember"
  ): TypedContractMethod<
    [groupId: BigNumberish, identityCommitment: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addMembers"
  ): TypedContractMethod<
    [groupId: BigNumberish, identityCommitments: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createGroup(address,uint256)"
  ): TypedContractMethod<
    [admin: AddressLike, merkleTreeDuration: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createGroup()"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "createGroup(address)"
  ): TypedContractMethod<[admin: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "groupCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeMember"
  ): TypedContractMethod<
    [
      groupId: BigNumberish,
      identityCommitment: BigNumberish,
      merkleProofSiblings: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateGroupAdmin"
  ): TypedContractMethod<
    [groupId: BigNumberish, newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateGroupMerkleTreeDuration"
  ): TypedContractMethod<
    [groupId: BigNumberish, newMerkleTreeDuration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMember"
  ): TypedContractMethod<
    [
      groupId: BigNumberish,
      oldIdentityCommitment: BigNumberish,
      newIdentityCommitment: BigNumberish,
      merkleProofSiblings: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateProof"
  ): TypedContractMethod<
    [groupId: BigNumberish, proof: ISemaphore.SemaphoreProofStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyProof"
  ): TypedContractMethod<
    [groupId: BigNumberish, proof: ISemaphore.SemaphoreProofStruct],
    [boolean],
    "view"
  >;

  getEvent(
    key: "GroupMerkleTreeDurationUpdated"
  ): TypedContractEvent<
    GroupMerkleTreeDurationUpdatedEvent.InputTuple,
    GroupMerkleTreeDurationUpdatedEvent.OutputTuple,
    GroupMerkleTreeDurationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProofValidated"
  ): TypedContractEvent<
    ProofValidatedEvent.InputTuple,
    ProofValidatedEvent.OutputTuple,
    ProofValidatedEvent.OutputObject
  >;

  filters: {
    "GroupMerkleTreeDurationUpdated(uint256,uint256,uint256)": TypedContractEvent<
      GroupMerkleTreeDurationUpdatedEvent.InputTuple,
      GroupMerkleTreeDurationUpdatedEvent.OutputTuple,
      GroupMerkleTreeDurationUpdatedEvent.OutputObject
    >;
    GroupMerkleTreeDurationUpdated: TypedContractEvent<
      GroupMerkleTreeDurationUpdatedEvent.InputTuple,
      GroupMerkleTreeDurationUpdatedEvent.OutputTuple,
      GroupMerkleTreeDurationUpdatedEvent.OutputObject
    >;

    "ProofValidated(uint256,uint256,uint256,uint256,uint256,uint256,uint256[8])": TypedContractEvent<
      ProofValidatedEvent.InputTuple,
      ProofValidatedEvent.OutputTuple,
      ProofValidatedEvent.OutputObject
    >;
    ProofValidated: TypedContractEvent<
      ProofValidatedEvent.InputTuple,
      ProofValidatedEvent.OutputTuple,
      ProofValidatedEvent.OutputObject
    >;
  };
}
