/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  SemaphoreVerifierKeyPts,
  SemaphoreVerifierKeyPtsInterface,
} from "../../contracts/SemaphoreVerifierKeyPts";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "actual",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expected",
        type: "uint256",
      },
    ],
    name: "Semaphore__VKPtBytesMaxDepthInvariantViolated",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f3404e7e03d93649cd8063b1b34187626f7fead61c508e4c5d0f85eee79627c764736f6c63430008180033";

type SemaphoreVerifierKeyPtsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SemaphoreVerifierKeyPtsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SemaphoreVerifierKeyPts__factory extends ContractFactory {
  constructor(...args: SemaphoreVerifierKeyPtsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SemaphoreVerifierKeyPts & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): SemaphoreVerifierKeyPts__factory {
    return super.connect(runner) as SemaphoreVerifierKeyPts__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SemaphoreVerifierKeyPtsInterface {
    return new Interface(_abi) as SemaphoreVerifierKeyPtsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SemaphoreVerifierKeyPts {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as SemaphoreVerifierKeyPts;
  }
}
