/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface SemaphoreGroupsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getGroupAdmin"
      | "getMerkleTreeDepth"
      | "getMerkleTreeRoot"
      | "getMerkleTreeSize"
      | "hasMember"
      | "indexOf"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GroupAdminPending"
      | "GroupAdminUpdated"
      | "GroupCreated"
      | "MemberAdded"
      | "MemberRemoved"
      | "MemberUpdated"
      | "MembersAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getGroupAdmin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerkleTreeDepth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerkleTreeRoot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerkleTreeSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasMember",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "indexOf",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getGroupAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerkleTreeDepth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerkleTreeRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerkleTreeSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "indexOf", data: BytesLike): Result;
}

export namespace GroupAdminPendingEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    oldAdmin: AddressLike,
    newAdmin: AddressLike
  ];
  export type OutputTuple = [
    groupId: bigint,
    oldAdmin: string,
    newAdmin: string
  ];
  export interface OutputObject {
    groupId: bigint;
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GroupAdminUpdatedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    oldAdmin: AddressLike,
    newAdmin: AddressLike
  ];
  export type OutputTuple = [
    groupId: bigint,
    oldAdmin: string,
    newAdmin: string
  ];
  export interface OutputObject {
    groupId: bigint;
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GroupCreatedEvent {
  export type InputTuple = [groupId: BigNumberish];
  export type OutputTuple = [groupId: bigint];
  export interface OutputObject {
    groupId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberAddedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    index: BigNumberish,
    identityCommitment: BigNumberish,
    merkleTreeRoot: BigNumberish
  ];
  export type OutputTuple = [
    groupId: bigint,
    index: bigint,
    identityCommitment: bigint,
    merkleTreeRoot: bigint
  ];
  export interface OutputObject {
    groupId: bigint;
    index: bigint;
    identityCommitment: bigint;
    merkleTreeRoot: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRemovedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    index: BigNumberish,
    identityCommitment: BigNumberish,
    merkleTreeRoot: BigNumberish
  ];
  export type OutputTuple = [
    groupId: bigint,
    index: bigint,
    identityCommitment: bigint,
    merkleTreeRoot: bigint
  ];
  export interface OutputObject {
    groupId: bigint;
    index: bigint;
    identityCommitment: bigint;
    merkleTreeRoot: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberUpdatedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    index: BigNumberish,
    identityCommitment: BigNumberish,
    newIdentityCommitment: BigNumberish,
    merkleTreeRoot: BigNumberish
  ];
  export type OutputTuple = [
    groupId: bigint,
    index: bigint,
    identityCommitment: bigint,
    newIdentityCommitment: bigint,
    merkleTreeRoot: bigint
  ];
  export interface OutputObject {
    groupId: bigint;
    index: bigint;
    identityCommitment: bigint;
    newIdentityCommitment: bigint;
    merkleTreeRoot: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MembersAddedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    startIndex: BigNumberish,
    identityCommitments: BigNumberish[],
    merkleTreeRoot: BigNumberish
  ];
  export type OutputTuple = [
    groupId: bigint,
    startIndex: bigint,
    identityCommitments: bigint[],
    merkleTreeRoot: bigint
  ];
  export interface OutputObject {
    groupId: bigint;
    startIndex: bigint;
    identityCommitments: bigint[];
    merkleTreeRoot: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SemaphoreGroups extends BaseContract {
  connect(runner?: ContractRunner | null): SemaphoreGroups;
  waitForDeployment(): Promise<this>;

  interface: SemaphoreGroupsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getGroupAdmin: TypedContractMethod<[groupId: BigNumberish], [string], "view">;

  getMerkleTreeDepth: TypedContractMethod<
    [groupId: BigNumberish],
    [bigint],
    "view"
  >;

  getMerkleTreeRoot: TypedContractMethod<
    [groupId: BigNumberish],
    [bigint],
    "view"
  >;

  getMerkleTreeSize: TypedContractMethod<
    [groupId: BigNumberish],
    [bigint],
    "view"
  >;

  hasMember: TypedContractMethod<
    [groupId: BigNumberish, identityCommitment: BigNumberish],
    [boolean],
    "view"
  >;

  indexOf: TypedContractMethod<
    [groupId: BigNumberish, identityCommitment: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getGroupAdmin"
  ): TypedContractMethod<[groupId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getMerkleTreeDepth"
  ): TypedContractMethod<[groupId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMerkleTreeRoot"
  ): TypedContractMethod<[groupId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMerkleTreeSize"
  ): TypedContractMethod<[groupId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasMember"
  ): TypedContractMethod<
    [groupId: BigNumberish, identityCommitment: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "indexOf"
  ): TypedContractMethod<
    [groupId: BigNumberish, identityCommitment: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "GroupAdminPending"
  ): TypedContractEvent<
    GroupAdminPendingEvent.InputTuple,
    GroupAdminPendingEvent.OutputTuple,
    GroupAdminPendingEvent.OutputObject
  >;
  getEvent(
    key: "GroupAdminUpdated"
  ): TypedContractEvent<
    GroupAdminUpdatedEvent.InputTuple,
    GroupAdminUpdatedEvent.OutputTuple,
    GroupAdminUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GroupCreated"
  ): TypedContractEvent<
    GroupCreatedEvent.InputTuple,
    GroupCreatedEvent.OutputTuple,
    GroupCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MemberAdded"
  ): TypedContractEvent<
    MemberAddedEvent.InputTuple,
    MemberAddedEvent.OutputTuple,
    MemberAddedEvent.OutputObject
  >;
  getEvent(
    key: "MemberRemoved"
  ): TypedContractEvent<
    MemberRemovedEvent.InputTuple,
    MemberRemovedEvent.OutputTuple,
    MemberRemovedEvent.OutputObject
  >;
  getEvent(
    key: "MemberUpdated"
  ): TypedContractEvent<
    MemberUpdatedEvent.InputTuple,
    MemberUpdatedEvent.OutputTuple,
    MemberUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MembersAdded"
  ): TypedContractEvent<
    MembersAddedEvent.InputTuple,
    MembersAddedEvent.OutputTuple,
    MembersAddedEvent.OutputObject
  >;

  filters: {
    "GroupAdminPending(uint256,address,address)": TypedContractEvent<
      GroupAdminPendingEvent.InputTuple,
      GroupAdminPendingEvent.OutputTuple,
      GroupAdminPendingEvent.OutputObject
    >;
    GroupAdminPending: TypedContractEvent<
      GroupAdminPendingEvent.InputTuple,
      GroupAdminPendingEvent.OutputTuple,
      GroupAdminPendingEvent.OutputObject
    >;

    "GroupAdminUpdated(uint256,address,address)": TypedContractEvent<
      GroupAdminUpdatedEvent.InputTuple,
      GroupAdminUpdatedEvent.OutputTuple,
      GroupAdminUpdatedEvent.OutputObject
    >;
    GroupAdminUpdated: TypedContractEvent<
      GroupAdminUpdatedEvent.InputTuple,
      GroupAdminUpdatedEvent.OutputTuple,
      GroupAdminUpdatedEvent.OutputObject
    >;

    "GroupCreated(uint256)": TypedContractEvent<
      GroupCreatedEvent.InputTuple,
      GroupCreatedEvent.OutputTuple,
      GroupCreatedEvent.OutputObject
    >;
    GroupCreated: TypedContractEvent<
      GroupCreatedEvent.InputTuple,
      GroupCreatedEvent.OutputTuple,
      GroupCreatedEvent.OutputObject
    >;

    "MemberAdded(uint256,uint256,uint256,uint256)": TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;
    MemberAdded: TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;

    "MemberRemoved(uint256,uint256,uint256,uint256)": TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;
    MemberRemoved: TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;

    "MemberUpdated(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      MemberUpdatedEvent.InputTuple,
      MemberUpdatedEvent.OutputTuple,
      MemberUpdatedEvent.OutputObject
    >;
    MemberUpdated: TypedContractEvent<
      MemberUpdatedEvent.InputTuple,
      MemberUpdatedEvent.OutputTuple,
      MemberUpdatedEvent.OutputObject
    >;

    "MembersAdded(uint256,uint256,uint256[],uint256)": TypedContractEvent<
      MembersAddedEvent.InputTuple,
      MembersAddedEvent.OutputTuple,
      MembersAddedEvent.OutputObject
    >;
    MembersAdded: TypedContractEvent<
      MembersAddedEvent.InputTuple,
      MembersAddedEvent.OutputTuple,
      MembersAddedEvent.OutputObject
    >;
  };
}
