/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISemaphoreVerifier,
  ISemaphoreVerifierInterface,
} from "../../../../@semaphore-protocol/contracts/interfaces/ISemaphoreVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "_pA",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "_pB",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "_pC",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[4]",
        name: "_pubSignals",
        type: "uint256[4]",
      },
      {
        internalType: "uint256",
        name: "merkleTreeDepth",
        type: "uint256",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISemaphoreVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): ISemaphoreVerifierInterface {
    return new Interface(_abi) as ISemaphoreVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISemaphoreVerifier {
    return new Contract(address, _abi, runner) as unknown as ISemaphoreVerifier;
  }
}
