/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "SemaphoreGroups",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SemaphoreGroups__factory>;
    getContractFactory(
      name: "ISemaphore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISemaphore__factory>;
    getContractFactory(
      name: "ISemaphoreGroups",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISemaphoreGroups__factory>;
    getContractFactory(
      name: "ISemaphoreVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISemaphoreVerifier__factory>;
    getContractFactory(
      name: "Semaphore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Semaphore__factory>;
    getContractFactory(
      name: "PoseidonT3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoseidonT3__factory>;
    getContractFactory(
      name: "SemaphoreVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SemaphoreVerifier__factory>;
    getContractFactory(
      name: "SemaphoreVerifierKeyPts",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SemaphoreVerifierKeyPts__factory>;
    getContractFactory(
      name: "Voting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Voting__factory>;
    getContractFactory(
      name: "PoseidonT3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoseidonT3__factory>;

    getContractAt(
      name: "SemaphoreGroups",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SemaphoreGroups>;
    getContractAt(
      name: "ISemaphore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISemaphore>;
    getContractAt(
      name: "ISemaphoreGroups",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISemaphoreGroups>;
    getContractAt(
      name: "ISemaphoreVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISemaphoreVerifier>;
    getContractAt(
      name: "Semaphore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Semaphore>;
    getContractAt(
      name: "PoseidonT3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PoseidonT3>;
    getContractAt(
      name: "SemaphoreVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SemaphoreVerifier>;
    getContractAt(
      name: "SemaphoreVerifierKeyPts",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SemaphoreVerifierKeyPts>;
    getContractAt(
      name: "Voting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Voting>;
    getContractAt(
      name: "PoseidonT3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PoseidonT3>;

    deployContract(
      name: "SemaphoreGroups",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SemaphoreGroups>;
    deployContract(
      name: "ISemaphore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISemaphore>;
    deployContract(
      name: "ISemaphoreGroups",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISemaphoreGroups>;
    deployContract(
      name: "ISemaphoreVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISemaphoreVerifier>;
    deployContract(
      name: "Semaphore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Semaphore>;
    deployContract(
      name: "PoseidonT3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT3>;
    deployContract(
      name: "SemaphoreVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SemaphoreVerifier>;
    deployContract(
      name: "SemaphoreVerifierKeyPts",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SemaphoreVerifierKeyPts>;
    deployContract(
      name: "Voting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Voting>;
    deployContract(
      name: "PoseidonT3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT3>;

    deployContract(
      name: "SemaphoreGroups",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SemaphoreGroups>;
    deployContract(
      name: "ISemaphore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISemaphore>;
    deployContract(
      name: "ISemaphoreGroups",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISemaphoreGroups>;
    deployContract(
      name: "ISemaphoreVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISemaphoreVerifier>;
    deployContract(
      name: "Semaphore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Semaphore>;
    deployContract(
      name: "PoseidonT3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT3>;
    deployContract(
      name: "SemaphoreVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SemaphoreVerifier>;
    deployContract(
      name: "SemaphoreVerifierKeyPts",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SemaphoreVerifierKeyPts>;
    deployContract(
      name: "Voting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Voting>;
    deployContract(
      name: "PoseidonT3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT3>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
